package frames;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Clases.ImagenFondo;
import Clases.ListasUsuario;

public class frmInicio extends javax.swing.JFrame {
   // Usuario obj1[] = new Usuario[20]; 

    ListasUsuario usuarios = new ListasUsuario();    
    ImagenFondo fondo;
    ImagenFondo fondo2;
    
    public frmInicio() {
        fondo = new ImagenFondo("src/ImgProyecto/empresa.jpg");
        this.setContentPane(fondo);        
        initComponents();
     /* obj1[0] = new Usuario("user01", "1234");
        obj1[1] = new Usuario("user02", "abcd");
        obj1[2] = new Usuario("user03", "1111");
        obj1[3] = new Usuario("user04", "0000");
        obj1[4] = new Usuario("user05", "1a2b");*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public Image getIconImage()
    {
        Image valorRetorno = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("ImgProyecto/empresa.jpg"));
        return valorRetorno;
    }       
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jpfPass = new javax.swing.JPasswordField();
        jlblMensaje = new javax.swing.JLabel();
        jbtnIng = new javax.swing.JButton();
        jbtnCan = new javax.swing.JButton();
        jbtnCan1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inicio de sesión");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jtfUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfUsuario.setBorder(null);
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 252, 30));

        jpfPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpfPass.setBorder(null);
        jpfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfPassActionPerformed(evt);
            }
        });
        jPanel2.add(jpfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 252, 30));

        jlblMensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblMensaje.setForeground(new java.awt.Color(255, 255, 255));
        jlblMensaje.setText("|");
        jPanel2.add(jlblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 276, 76));

        jbtnIng.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jbtnIng.setText("Ingresar");
        jbtnIng.setBorder(null);
        jbtnIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 95, 35));

        jbtnCan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnCan.setText("Registrar");
        jbtnCan.setBorder(null);
        jbtnCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCanActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 160, 30));

        jbtnCan1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jbtnCan1.setText("Cancelar");
        jbtnCan1.setBorder(null);
        jbtnCan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCan1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 95, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngActionPerformed
        if (jtfUsuario.getText().equals("") || jpfPass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Debe insertar primero todos los datos correspondientes");
        }else
        {
            usuarios.validarUsu(jtfUsuario.getText(), jpfPass.getText(),this, usuarios);
        }
    }//GEN-LAST:event_jbtnIngActionPerformed

    private void jbtnCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCanActionPerformed
        frmUsuario usu = new frmUsuario(this, null, usuarios);
        //jifUsuario usu = new jifUsuario(this, null, usuarios);
        this.setVisible(false);
        usu.setVisible(true);
    }//GEN-LAST:event_jbtnCanActionPerformed

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void jpfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfPassActionPerformed

    private void jbtnCan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnCan;
    private javax.swing.JButton jbtnCan1;
    private javax.swing.JButton jbtnIng;
    private javax.swing.JLabel jlblMensaje;
    private javax.swing.JPasswordField jpfPass;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
