package proyecto;

import Clases.Pila;
import frames.frmMenu;

public class jifRenta extends javax.swing.JInternalFrame {

    frmMenu Regresar;
    Pila Renta;
    public jifRenta(frmMenu me, Pila rent) {
        Regresar = me;
        Renta = rent;        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jlsLibrosE = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jlsLibrosDis = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jbtnSeleccionar = new javax.swing.JButton();
        jbtnQuitar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlblCantL = new javax.swing.JLabel();
        jlblTotalR = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlblAnoFR = new javax.swing.JLabel();
        jlbTotalR = new javax.swing.JLabel();
        jlblDiaFR = new javax.swing.JLabel();
        jlblMesFR = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jbtnRealizarP = new javax.swing.JButton();
        jlblAnoFEE = new javax.swing.JLabel();
        jlblDiaFEE = new javax.swing.JLabel();
        jlblMesFEE = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jbtnRegresarL = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jDesktopPane1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlsLibrosE.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Elegidos:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jlsLibrosE);

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 240, 230));

        jlsLibrosDis.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Disponibles:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jlsLibrosDis);

        jPanel2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 250, 230));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 102));
        jLabel9.setText("Punto de Venta");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jbtnSeleccionar.setText("Seleccionar");
        jPanel2.add(jbtnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, 20));

        jbtnQuitar.setText("Quitar de la  lista");
        jPanel2.add(jbtnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, 20));

        jPanel3.setBackground(new java.awt.Color(204, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCantL.setText("|");
        jPanel3.add(jlblCantL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 30, 20));

        jlblTotalR.setText("|");
        jPanel3.add(jlblTotalR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 70, 20));

        jLabel11.setText("Cantidad de libros:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 20));

        jLabel12.setText("Total de renta:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 20));

        jlblAnoFR.setText("|");
        jPanel3.add(jlblAnoFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 60, 20));

        jlbTotalR.setText("|");
        jPanel3.add(jlbTotalR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 70, 20));

        jlblDiaFR.setText("|");
        jPanel3.add(jlblDiaFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 30, 20));

        jlblMesFR.setText("|");
        jPanel3.add(jlblMesFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 30, 20));

        jLabel13.setText("Total de retardos:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        jLabel14.setText("Fecha de renta:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 20));

        jbtnRealizarP.setText("Realizar el pedido");
        jPanel3.add(jbtnRealizarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, 20));

        jlblAnoFEE.setText("|");
        jPanel3.add(jlblAnoFEE, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 60, 20));

        jlblDiaFEE.setText("|");
        jPanel3.add(jlblDiaFEE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 30, 20));

        jlblMesFEE.setText("|");
        jPanel3.add(jlblMesFEE, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 30, 20));

        jLabel17.setText("Fecha de entrega establecida:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        jbtnRegresarL.setText("Regresar Libro(s)");
        jPanel3.add(jbtnRegresarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton jbtnQuitar;
    private javax.swing.JButton jbtnRealizarP;
    private javax.swing.JButton jbtnRegresarL;
    private javax.swing.JButton jbtnSeleccionar;
    private javax.swing.JLabel jlbTotalR;
    private javax.swing.JLabel jlblAnoFEE;
    private javax.swing.JLabel jlblAnoFR;
    private javax.swing.JLabel jlblCantL;
    private javax.swing.JLabel jlblDiaFEE;
    private javax.swing.JLabel jlblDiaFR;
    private javax.swing.JLabel jlblMesFEE;
    private javax.swing.JLabel jlblMesFR;
    private javax.swing.JLabel jlblTotalR;
    private javax.swing.JList<String> jlsLibrosDis;
    private javax.swing.JList<String> jlsLibrosE;
    // End of variables declaration//GEN-END:variables
}
